### ISSUE TITLE
aggRviz_filter2 enhancements

### ISSUE THREAD

**Issue by susan-fung** [amygoldlist/aggRviz#15]
I would like to propose two feature enhancements for aggRviz_filter2:
1. the output of aggRviz automatically create factor level for the categorical dimensions, however, an "" level is included. Can we use `droplevels` to remove the "" level?
2.  Can we relevel two categorical factors? (More detail in provided in Slack)

**Comment by amygoldlist** [comment]
Yeah, I think that would help.  I also have a draft of a function that would only include one place variable.  We may need some more helper fuinctions

**Comment by amygoldlist** [comment]
Update:  We will relevel the categorical variables on their own, not in any functions.  I will add `droplevels` (or the forcats version if it runs cleaner) to the filter.

**Comment by amygoldlist** [comment]
Done!
